# Generated by Django 2.0.5 on 2018-05-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('summoner_id', models.IntegerField(default=0)),
                ('account_id', models.IntegerField(default=0)),
                ('top_kill', models.IntegerField(default=0)),
                ('region', models.CharField(choices=[('na1', 'NA1'), ('br1', 'BR1'), ('eun1', 'EUN1'), ('euw1', 'EUW1'), ('jp1', 'JP1'), ('kr', 'KR'), ('la1', 'LA1'), ('la2', 'LA2'), ('oc1', 'OC1'), ('tr1', 'TR1'), ('ru', 'RU')], default='NA1', max_length=6)),
                ('item0', models.IntegerField(default=0)),
                ('item1', models.IntegerField(default=0)),
                ('item2', models.IntegerField(default=0)),
                ('item3', models.IntegerField(default=0)),
                ('item4', models.IntegerField(default=0)),
                ('item5', models.IntegerField(default=0)),
                ('item6', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together={('username', 'region')},
        ),
    ]
